Repository pokerogue-KO/ME-KOREAN, pull requests merged in 2024-09, with the labels that each got.

#1 [event]dark-deal-dialogue
  src/locales/ko/mystery-encounters/dark-deal-dialogue.json
Labels: 1차완료

#4 [event]an offer you can't refuse, dance lesson, trash to treasure
  src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
  src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
  src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
Labels: 1차완료

#5 [event] berries abound, absolute avarice, delibird-y
  src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
  src/locales/ko/mystery-encounters/berries-abound-dialogue.json
  src/locales/ko/mystery-encounters/delibirdy-dialogue.json
Labels: 1차완료

#6 [event] department store sale, fight or flight, mystery chest
  src/locales/ko/mystery-encounters/department-store-sale-dialogue.json
  src/locales/ko/mystery-encounters/fight-or-flight-dialogue.json
  src/locales/ko/mystery-encounters/mysterious-chest-dialogue.json
Labels: 1차완료

#7 [event]mysterious chagllengers, field trip, lost at sea
  src/locales/ko/mystery-encounters/field-trip-dialogue.json
  src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
  src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
Labels: 1차완료

#9 a-trainers-test , the-winstrate-challenge
  src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
  src/locales/ko/mystery-encounters/the-winstrate-challenge-dialogue.json
Labels: 1차완료, 리뷰필요

#8 [Event] bug type super fan, clowning around, firely fallout
  src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
  src/locales/ko/mystery-encounters/clowning-around-dialogue.json
  src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
Labels: 리뷰필요

#10 fun game
  src/locales/ko/mystery-encounters/fun-and-games-dialogue.json
Labels: 1차완료, 리뷰필요

#11 GTS 초안 번역
  src/locales/ko/mystery-encounters/global-trade-system-dialogue.json
Labels: 1차완료

#13 add translation for safari-zone
  src/locales/ko/mystery-encounters/safari-zone-dialogue.json
Labels: 1차완료, 리뷰필요

#12 part timer 초안 번역
  src/locales/ko/mystery-encounters/part-timer-dialogue.json
Labels: 1차완료, 리뷰필요

#14 shady vitamin dealer 초안 번역
  src/locales/ko/mystery-encounters/shady-vitamin-dealer-dialogue.json
Labels: 1차완료, 리뷰필요

#15 [event]weird dream, uncommon breed, traning session
  src/locales/ko/mystery-encounters/training-session-dialogue.json
  src/locales/ko/mystery-encounters/uncommon-breed-dialogue.json
  src/locales/ko/mystery-encounters/weird-dream-dialogue.json
Labels: 리뷰필요

#16 [event] strong stuff, pokemon salesman
  src/locales/ko/mystery-encounters/the-pokemon-salesman-dialogue.json
  src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
Labels: 리뷰필요

#17 [event] teleporting hijinks, slumbering snorlax
  src/locales/ko/mystery-encounters/slumbering-snorlax-dialogue.json
  src/locales/ko/mystery-encounters/teleporting-hijinks-dialogue.json
Labels: 리뷰필요
